// Aliases
#define CM_GRV GRAVE         // `
#define CM_1 N1              // 1
#define CM_2 N2              // 2
#define CM_3 N3              // 3
#define CM_4 N4              // 4
#define CM_5 N5              // 5
#define CM_6 N6              // 6
#define CM_7 N7              // 7
#define CM_8 N8              // 8
#define CM_9 N9              // 9
#define CM_0 N0              // 0
#define CM_MINS MINUS        // -
#define CM_EQL EQUAL         // =
#define CM_Q Q               // Q
#define CM_W W               // W
#define CM_F E               // F
#define CM_P R               // P
#define CM_G T               // G
#define CM_J Y               // J
#define CM_L U               // L
#define CM_U I               // U
#define CM_Y O               // Y
#define CM_SEMI P            // ;
#define CM_LBRC LBKT         // [
#define CM_RBRC RBKT         // ]
#define CM_BSLS BACKSLASH    // (backslash)
#define CM_A A               // A
#define CM_R S               // R
#define CM_S D               // S
#define CM_T F               // T
#define CM_D G               // D
#define CM_H H               // H
#define CM_N J               // N
#define CM_E K               // E
#define CM_I L               // I
#define CM_O SEMI            // O
#define CM_QUOT SQT          // '
#define CM_Z Z               // Z
#define CM_X X               // X
#define CM_C C               // C
#define CM_V V               // V
#define CM_B B               // B
#define CM_K N               // K
#define CM_M M               // M
#define CM_COMM COMMA        // ,
#define CM_DOT DOT           // .
#define CM_SLSH FSLH         // /
#define CM_TILD LS(CM_GRV)   // ~
#define CM_EXLM LS(CM_1)     // !
#define CM_AT LS(CM_2)       // @
#define CM_HASH LS(CM_3)     // #
#define CM_DLR LS(CM_4)      // $
#define CM_PERC LS(CM_5)     // %
#define CM_CIRC LS(CM_6)     // ^
#define CM_AMPR LS(CM_7)     // &
#define CM_ASTR LS(CM_8)     // *
#define CM_LPRN LS(CM_9)     // (
#define CM_RPRN LS(CM_0)     // )
#define CM_UNDS LS(CM_MINS)  // _
#define CM_PLUS LS(CM_EQL)   // +
#define CM_COLON LS(CM_SEMI) // :
#define CM_LCBR LS(CM_LBRC)  // {
#define CM_RCBR LS(CM_RBRC)  // }
#define CM_PIPE LS(CM_BSLS)  // |
#define CM_DQUO LS(CM_QUOT)  // "
#define CM_LABK LS(CM_COMM)  // <
#define CM_RABK LS(CM_DOT)   // >
#define CM_QUES LS(CM_SLSH)  // ?
